### ISSUE TITLE
Code lookup not working

### ISSUE THREAD

**Issue by kprueckl-dt** [Dynatrace/Dynatrace-Visual-Studio-2017#5]
The code lookup is not always working for methods in partial classes - especially for ASP.NET code-behind files (.aspx.cs). Thanks to a customer who has reported this in the supportportal as SUPDT-37099.

**Comment by dglugla** [comment]
https://github.com/Dynatrace/Dynatrace-AppMon-Visual-Studio-2017/pull/6
release will be published soon
